<Project>
  <PropertyGroup>
    <GitTag>1.0.0</GitTag>
    <SpecsProductName>specs</SpecsProductName>
    <SpecsFileDescription>A re-writing of the specs pipeline stage from CMS, only changed quite a bit</SpecsFileDescription>
    <SpecsCopyright>Copyright (c) 2018-2026 Yoav Nir</SpecsCopyright>
    <SpecsProductVersion Condition="'$(SpecsProductVersion)' == ''">$(GitTag)</SpecsProductVersion>
    <SpecsFileVersion Condition="'$(SpecsFileVersion)' == ''">1,0,0,0</SpecsFileVersion>
  </PropertyGroup>
</Project>
