name: C/C++ CI

on:
  push:
    branches: [ v0.9-dev ]
  pull_request:
    branches: [ v0.9-dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: configure
      run: cd specs/src ; python setup.py
    - name: make
      run: cd specs/src ; make all
    - name: make check
      run: cd specs/src ; make run_tests
