name: C/C++ CI

on:
  push:
    branches: [ dev, stable, dev-0.9.6, dev-0.9.9, dev-1.0.0, dev-packaging]
  pull_request:
    branches: [ dev, stable, dev-0.9.6, dev-0.9.9, dev-1.0.0, dev-packaging]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Install Python dev headers
      run: sudo apt-get install -y python3-dev
    - name: configure
      run: cd specs/src ; python3 setup.py --python python3 
    - name: make
      run: cd specs/src ; make all
    - name: make check
      run: cd specs/src ; make run_tests

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: configure
      working-directory: specs/src
      run: python3 setup.py -c CLANG --python python3

    - name: make
      working-directory: specs/src
      run: make all

    - name: make check
      working-directory: specs/src
      run: make run_tests      

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.3
    - name: Build specs (Debug)
      run: msbuild specs/specs.sln /p:Configuration=Debug /p:Platform=x64
    - name: Build specs (Release)
      run: msbuild specs/specs.sln /p:Configuration=Release /p:Platform=x64
    - name: Test specs executable
      run: specs/bin/Release/specs.exe "@version"
