name: C/C++ CI

on:
  push:
    branches: [ dev, stable, dev-0.9.2, dev-0.9.3, dev-0.9.4, dev-0.9.5, dev-0.9.9, dev-1.0.0]
  pull_request:
    branches: [ dev, stable, dev-0.9.2, dev-0.9.3, dev-0.9.4, dev-0.9.5, dev-0.9.9, dev-1.0.0]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: configure
      run: cd specs/src ; python setup.py
    - name: make
      run: cd specs/src ; make all
    - name: make check
      run: cd specs/src ; make run_tests
